import type {Metadata} from "next";
import {Inter, Playfair_Display} from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/NavigationBar";
import Image from 'next/image';
import CacheDebugger from "@/components/CacheDebugger";

const inter = Inter({subsets: ["latin"], variable: '--font-sans'});
const playfair = Playfair_Display({subsets: ["latin"], variable: '--font-serif'});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${inter.variable} ${playfair.variable} font-sans bg-slate-50 text-slate-900 antialiased`}>
        <NavigationBar/>

        {/* --- HERO SECTION --- */}
        <section className="relative h-[700px] flex flex-col items-center justify-center text-center px-4 pt-20">

            {/* Фоновое изображение */}
            <div className="absolute inset-0 z-0">
                <Image
                    src="/header.png" // ЗАМЕНИ на свой файл в public/hero-bg.jpg
                    alt="Epic D&D Background"
                    fill
                    className="object-cover"
                    priority
                />
                {/* Градиент для затемнения, чтобы текст читался */}
                <div
                    className="absolute inset-0 bg-gradient-to-b from-slate-900/70 via-slate-900/50 to-slate-900/90"></div>
            </div>

            {/* Контент Hero */}
            <div className="relative z-10 max-w-4xl mx-auto mt-10 space-y-6 animate-fade-in-up">
                <h1 className="text-5xl md:text-7xl font-serif font-bold text-white leading-tight drop-shadow-lg">
                    Find your Ultimate Challenge
                </h1>
                <p className="text-xl text-slate-200 max-w-2xl mx-auto leading-relaxed drop-shadow-md">
                    Explore thousands of monsters, filter by challenge rating, <br className="hidden md:block"/> and
                    create unforgettable adventures.
                </p>

                {/* --- SEARCH BAR CONTAINER --- */}
                <div
                    className="mt-12 bg-white rounded-full p-2 flex items-center justify-between max-w-3xl mx-auto shadow-2xl shadow-slate-900/30">

                    {/* Левая часть: Иконка и текстовый поиск */}
                    <div className="flex items-center flex-grow px-4 border-r border-slate-200">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
                             className="w-6 h-6 text-slate-400 mr-3">
                            <path fillRule="evenodd"
                                  d="M9 3.5a5.5 5.5 0 100 11 5.5 5.5 0 000-11zM2 9a7 7 0 1112.452 1.591l-.87.87A7 7 0 012 9zm8 7a7 7 0 100-14 7 7 0 000 14z"
                                  clipRule="evenodd"/>
                        </svg>
                        <input
                            type="text"
                            placeholder="Search monsters..."
                            className="w-full bg-transparent focus:outline-none text-slate-700 text-lg placeholder:text-slate-400"
                        />
                    </div>

                    {/* Центральная часть: Слайдер CR */}
                    <div className="hidden md:block">
                        {/*<InlineCrSlider initialValue={cr} />*/}
                    </div>

                    {/* Правая часть: Кнопка поиска */}
                    <button
                        className="bg-blue-600 hover:bg-blue-700 text-white font-bold text-lg py-3 px-8 rounded-full transition-all shadow-md ml-2">
                        SEARCH
                    </button>
                </div>

            </div>
        </section>
        {children}
        <CacheDebugger />
        </body>
        </html>
    );
}
